Fix #1179194: Add missing path & verify step
SUSE/doc-sleha pull request #148
Opened 2020-11-25 15:09 UTC by tomschr

### Description

It seems, watchdog drivers can also be found in a different directory `/lib/modules/<version>/kernel/drivers/char/ipmi/`).
=> Add dir into the floating text

Add verifying step.

See bsc#1179194

### Backports

- [x] To maintenance/SLEHA12SP4
- [x] To maintenance/SLEHA15
- [x] To maintenance/SLEHA15SP1

2020-12-02 16:04 UTC, taroth21 commented on xml/ha_storage_protection.xml
> +      If your watchdog device is not available, check module name and options.
```suggestion
      If your watchdog device is not available, check the module name and options.
```

2020-12-02 16:05 UTC, taroth21 requested changes
Hi Thomas, I spotted two minor issues, otherwise LGTM! Thx!

2020-12-02 16:05 UTC, taroth21 commented on xml/ha_storage_protection.xml
>     gives you a list of choices, too. Alternatively, ask your hardware or
```suggestion
   give you a list of choices, too. Alternatively, ask your hardware or
```

2020-12-04 07:15 UTC, merged

2020-12-04 07:25 UTC, tomschr commented
Bug in Bugzilla closed.