Disaster Recovery for Cluster MD (bsc#1168482)
SUSE/doc-sleha pull request #173
Opened 2021-05-19 14:05 UTC by taroth21

### Description

https://bugzilla.suse.com/show_bug.cgi?id=1168482
https://jira.suse.com/browse/DOCTEAM-119

### Backports

- [x] To maintenance/SLEHA15SP2
- [x] To maintenance/SLEHA15SP1
- [x] To maintenance/SLEHA15
- [x] To maintenance/SLEHA12SP5
- [x] To maintenance/SLEHA12SP4

2021-05-19 14:09 UTC, taroth21 commented
@zzhou1 : Could you please have a look and review? 

Draft PDF Output is visible here:
![image](https://user-images.githubusercontent.com/1875958/118827347-95b59580-b8bc-11eb-8d48-a452b510c4c3.png)

2021-05-20 07:02 UTC, zzhou1 commented
LGTM

2021-05-20 10:02 UTC, lproven requested changes
Very small suggestions: moving an article and changing one word.

2021-05-20 10:02 UTC, lproven commented on xml/ha_cluster_md.xml
> +   In case of a disaster recovery, you might face the situation that you do not have
```suggestion
   In the event of disaster recovery, you might face the situation that you do not have
```

2021-05-20 10:02 UTC, lproven commented on xml/ha_cluster_md.xml
> +   You can convert Cluster MD RAID to a normal RAID by using the <option>--assemble</option>
```suggestion
   You can convert a Cluster MD RAID to a normal RAID by using the <option>--assemble</option>
```

2021-05-20 11:49 UTC, merged

2021-05-20 11:50 UTC, taroth21 commented
Merged now to get it into the localization drop for SP3, backports to follow tomorrow.