WIP: Full install guide
SUSE/doc-sleha pull request #410
Opened 2024-08-28 05:12 UTC by tahliar

### PR creator: Description

Adding a full deployment guide so that all the options are clear. This is a long-term project and is currently a WIP. 
Opening a PR just for easier viewing of progress.

I originally kept track of the relevant product changes for each SP, but I've decided that it doesn't make sense to backport this, both because of complexity and to avoid issues with the localised content in earlier versions.

### PR creator: Are there any relevant issues/feature requests?

* jsc#PED-2842

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [x] 15 next *(current `main`, no backport necessary)*
  - [ ] 15 SP6
  - [ ] 15 SP5
  - [ ] 15 SP4
  - [ ] 15 SP3
  - [ ] 15 SP2
- SLE-HA 12
  - [ ] 12 SP5

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2025-03-26 05:24 UTC, tahliar commented
**Main change: major expansion of the content in "Part I: Installation and setup"**

For this I'll attach a PDF, as it's a whole Part. This PDF contains _only_ Part I: 
[part-install_en.pdf](https://github.com/user-attachments/files/19460744/part-install_en.pdf)

List of changes:

- Added a new chapter "2 Installation overview". This gives an introduction to the rest of the chapters in this part, i.e. the high-level procedure for setting up a cluster.
- Added a new chapter "4 Logging in to the cluster nodes". Before installing anything, this explains the root vs sudo user options, and SSH agent forwarding.
- Added a new chapter "6 Using the bootstrap scripts". This goes into detail about `crm cluster init` and `crm cluster join`, with options beyond just the quickstart defaults. It also includes a quick section on `crm cluster remove`.
- Slightly restructured chapter "7 Using the YaST cluster module" to follow the initial wizard better, but moved the non-YaST parts to the end (i.e. transferring the config to all nodes and starting the cluster).
- Added a new section "7.4 Configuring an arbitrator for quorum decisions" because the QDevice window wasn't documented before.

2025-04-28 19:25 UTC, gao-yan reviewed
Thanks for the nice work, @tahliar !

Some comments in below.

@zzhou1 @liangxin1300 , you definitely want go through this.

2025-04-29 01:57 UTC, tahliar commented on xml/ha_installation_overview.xml
> +            with more than two nodes. For disk-based SBD, we recommend multiple SBD devices.
That's definitely a good point, but might get a bit wordy for this overview. I'll mention it more prominently in the SBD chapter.

2025-04-29 09:14 UTC, liangxin1300 commented on xml/ha_config_cli.xml
> +<screen>&prompt.root;<command>crm cluster join -c <replaceable>NODE1</replaceable> -i eth0 -i eth1</command></screen>
Yes, when init node using two rings, the join node must specify two interfaces

2025-04-29 09:29 UTC, liangxin1300 commented on xml/ha_installation_overview.xml
> +        one node with &yast;, then use the bootstrap scripts to add more nodes. You can also clone
This part of doc means, the first node using yast, then other nodes using `crm cluster join`? 
Please don't do that!
We should always recommend user to either use yast or use crmsh bootstrap on all nodes, don't mix them!

2025-04-29 13:54 UTC, liangxin1300 commented on xml/ha_bootstrap_install.xml
> +            The script creates a small partition on the device to be used for SBD.
If the device is already initialized by `sbd create`:
In interactive mode, crmsh will ask:
```
Do you wish to use SBD (y/n)? y
Path to storage device (e.g. /dev/disk/by-id/...), or "none" for diskless sbd, use ";" as separator for multi path []/dev/sda5
SBD is already configured to use /dev/sda5 - overwrite (y/n)?
```
If choose `n`, the metadata in sbd device wouldn't be overwritten;
If choose `y`, the metadata in sbd device will be overwritten by the defined parameter in /etc/crm/profiles.yml

In non-interactive mode(crm cluster init -s <device> -y), the metadata in sbd device will also be overwritten

2025-04-29 23:47 UTC, tahliar commented on xml/ha_installation_overview.xml
> +        one node with &yast;, then use the bootstrap scripts to add more nodes. You can also clone
Oh, thanks for this! The suggestion that you can use a mixed approach was already in the docs all the way back to 12 SP5 and probably earlier. I'll remove it everywhere.

2025-04-30 00:22 UTC, tahliar commented on xml/ha_config_cli.xml
> +<screen>&prompt.root;<command>crm cluster init corosync</command></screen>
Yep, when I set up a bond and run `crm cluster init corosync`, it mentions bond0:

![image](https://github.com/user-attachments/assets/3d53c211-5688-4f82-ac19-d92dd416db4e)

But when I don't have a bond configured, it mentions eth0:

![image](https://github.com/user-attachments/assets/29493e58-ad0d-4a9b-a757-a13cd74bba24)

2025-04-30 00:55 UTC, tahliar commented on xml/ha_config_cli.xml
> +<screen>&prompt.root;<command>crm cluster join -c <replaceable>NODE1</replaceable> -i eth0 -i eth1</command></screen>
Thanks!

2025-04-30 02:19 UTC, liangxin1300 commented on xml/ha_bootstrap_install.xml
> +            The script creates a small partition on the device to be used for SBD.
No, crmsh don't create a disk partition

2025-04-30 03:09 UTC, tahliar commented on xml/ha_bootstrap_install.xml
> +            The script creates a small partition on the device to be used for SBD.
Looks like this statement also goes back to SLE 12: https://documentation.suse.com/sle-ha/12-SP5/html/SLE-HA-all/art-ha-install-quick.html#sec-ha-inst-quick-sbd-req

I'll backport this change too, then. Thanks!

2025-04-30 11:03 UTC, zzhou1 requested changes

2025-04-30 11:03 UTC, zzhou1 commented on xml/ha_yast_cluster.xml
> +    following preparations: </para>
Worth to share another simplest one is `crm cluster init -y csync2` which basically implement "PROCEDURE 7.10"

2025-04-30 13:12 UTC, dariavladykina reviewed
LGTM, only minor suggestions for the entire thing. Thanks!

2025-04-30 13:12 UTC, dariavladykina commented on xml/ha_yast_cluster.xml
> +       <guimenu>Remove</guimenu> files from the list of files to be synchronized
```suggestion
       <guimenu>Remove</guimenu> files from the list of files to be synchronized,
```

2025-05-01 01:08 UTC, tahliar commented on xml/ha_yast_cluster.xml
> +    following preparations: </para>
Ohh, thanks, that's much easier!

2025-05-01 01:18 UTC, tahliar commented on xml/ha_bootstrap_install.xml
> +      only the default options, see <xref linkend="article-installation"/>.
AFAIK doing an xref like this to other HA docs only creates a clickable link in the chunked HTML version, which uses the DC file SLE-HA-all. Otherwise it only resolves as a title in HTML-single and PDF (e.g. in the published version, see https://documentation.suse.com/sle-ha/15-SP6/single-html/SLE-HA-administration/#cha-ha-ycluster vs https://documentation.suse.com/sle-ha/15-SP6/html/SLE-HA-all/cha-ha-ycluster.html). 

I sometimes get around this by using a hard link instead.

2025-05-01 03:17 UTC, tahliar commented on xml/ha_bootstrap_install.xml
> +            The script creates a small partition on the device to be used for SBD.
@gao-yan @liangxin1300 

Hmm, this is also mentioned in the SBD chapter: https://documentation.suse.com/sle-ha/15-SP6/html/SLE-HA-all/cha-ha-storage-protect.html#id-1.4.4.11.3.6

I found this commit from 10 years ago: https://github.com/SUSE/doc-sleha/commit/ad62f1319dd0d668f6f0265853e1476d4f48daee
But even then the partition is already mentioned, so it's very old indeed. 

Is this something that used to be true but isn't anymore? Or am I confusing two different things?

2025-05-01 03:56 UTC, tahliar commented on xml/ha_bootstrap_install.xml
> +            The script creates a small partition on the device to be used for SBD.
I think the doc might be mixing up disk partitions and node slots? Whatever the case, I'll take the partition line out of the `crm cluster init` sections for all versions, since it doesn't really need to be there.

2025-05-01 06:34 UTC, gao-yan commented on xml/ha_bootstrap_install.xml
> +            The script creates a small partition on the device to be used for SBD.
> @gao-yan @liangxin1300
> 
> Hmm, this is also mentioned in the SBD chapter: https://documentation.suse.com/sle-ha/15-SP6/html/SLE-HA-all/cha-ha-storage-protect.html#id-1.4.4.11.3.6
> 
> I found this commit from 10 years ago: [ad62f13](https://github.com/SUSE/doc-sleha/commit/ad62f1319dd0d668f6f0265853e1476d4f48daee) But even then the partition is already mentioned, so it's very old indeed.
> 
> Is this something that used to be true but isn't anymore? Or am I confusing two different things?

Indeed I can tell the description there has been misleading.

We'd better change "SBD partition" to "SBD device" meanwhile probably telling something like this instead:

 "In an environment where all nodes have access to shared storage, a small logic unit or a small partition on a logic unit is formatted for use with SBD. The size of the device ..."

?

2025-05-01 06:48 UTC, gao-yan commented on xml/ha_config_cli.xml
> +<screen>&prompt.root;<command>crm cluster join -c <replaceable>NODE1</replaceable> -i eth0 -i eth1</command></screen>
Since "redundant communication channel" is mentioned in the section "Setting up the first node with crm cluster init", should this be mentioned in the section "Adding nodes with crm cluster join" too, given that specifications are necessary for the case?

2025-05-01 06:51 UTC, tahliar commented on xml/ha_bootstrap_install.xml
> +            The script creates a small partition on the device to be used for SBD.
Thanks @gao-yan, that sounds better. I'll make that change for all versions.

2025-05-01 07:03 UTC, tahliar commented on xml/ha_config_cli.xml
> +<screen>&prompt.root;<command>crm cluster join -c <replaceable>NODE1</replaceable> -i eth0 -i eth1</command></screen>
Definitely! I should have thought of that, thanks for noticing!

2025-05-01 14:18 UTC, zzhou1 commented on xml/ha_bootstrap_install.xml
> +          geographical location and makes it easier to distinguish a site inside a &geo; cluster.
Ah, thank Yan to bring up this topic. I don't have the chance to dive into this topic much. Apparently, yes, cluster_name is required for DLM. 

For corosync alone, cluster_name gives the convenience to generate multicast address for corosync.

2025-05-02 01:24 UTC, tahliar commented on xml/ha_config_cli.xml
> +<screen>&prompt.root;<command>crm cluster join -c <replaceable>NODE1</replaceable> -i eth0 -i eth1</command></screen>
I've added more options for the `join` script: 

![image](https://github.com/user-attachments/assets/60e0833c-d577-4568-8677-0e367720e155)

2025-05-02 04:34 UTC, gao-yan approved these changes
LGTM. Awesome work, @tahliar !

2025-05-02 09:38 UTC, dariavladykina approved these changes

2025-05-02 09:42 UTC, dariavladykina approved these changes

2025-05-02 09:44 UTC, dariavladykina approved these changes

2025-05-06 00:33 UTC, merged