Clarify how fence_kdump works
SUSE/doc-sleha pull request #415
Opened 2024-09-13 01:39 UTC by tahliar

### PR creator: Description

Hopefully this makes the fence_kdump example clearer. 

### PR creator: Are there any relevant issues/feature requests?

* bsc#1228931
* jsc#DOCTEAM-537

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [x] 15 next *(current `main`, no backport necessary)*
  - [x] 15 SP6
  - [x] 15 SP5
  - [x] 15 SP4
  - [x] 15 SP3
  - [x] 15 SP2
- SLE-HA 12
  - [x] 12 SP5

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

2024-09-13 01:42 UTC, tahliar commented
![image](https://github.com/user-attachments/assets/f55699b1-f935-4a46-96ef-ee38eb903358)
![image](https://github.com/user-attachments/assets/667bc292-0856-4730-8b77-004e93f4784e)

2024-09-19 10:39 UTC, zzhou1 requested changes

2024-09-19 10:39 UTC, zzhou1 commented on xml/ha_fencing.xml
>         from using a fencing device, add location constraints.
```suggestion
       Name of the node to listen a message from <literal>fence_kdump_send</literal>. 
       Configure more &stonith; resources for other nodes if need.
```

2024-09-19 10:39 UTC, zzhou1 commented on xml/ha_fencing.xml
> +        then no Kdump is in progress and the &stonith; device fences the node.
```suggestion
        considers the node to be fenced. If no message is received, then fence_dump get 
        timeout and that indicates the fence operation failed. The next &stonith;  
        device in the fence_topology fences the node eventually.
```

2024-09-19 10:39 UTC, zzhou1 commented on xml/ha_fencing.xml
>      <command>pcmk_host_check="static-list" \
```suggestion
    pcmk_host_list="&node1;" \
    <command>pcmk_host_check="static-list" \
```

REF: bsc#1007422

pcmk_host_list is documented in 
https://clusterlabs.org/pacemaker/doc/2.1/Pacemaker_Explained/singlehtml/#special-instance-attributes-for-fencing-resources

2024-09-19 10:39 UTC, zzhou1 commented on xml/ha_fencing.xml
> +     see <command>crm ra info stonith:fence_kdump</command>.
This sentence was legacy long ago and doesn't fit nowadays for sure.

```suggestion
     Use the <literal>stonith:fence_kdump</literal> fence agent. 
     A configuration example is shown below. For more information,
     see <command>crm ra info stonith:fence_kdump</command>.
```

2024-09-20 00:57 UTC, tahliar commented
Thanks @zzhou1! I applied your fixes and made a couple of little edits. Let me know if you're happy with it :)

2024-09-20 02:36 UTC, zzhou1 approved these changes
Thx, Tahlia!

2024-09-20 11:57 UTC, dariavladykina approved these changes
LGTM!

2024-09-24 02:51 UTC, merged